/*
	Skills
	------
*/

import { type SkillsConfig, SkillType } from '../../types/content/skills.ts';

export const SKILLS_CONFIG: SkillsConfig = {
	[SkillType.Languages]: [
		// Common
		'C/C++',
		'CSS',
		'GraphQL',
		'HTML',
		'Java',
		'JavaScript/TypeScript',
		'JSX/TSX',
		'Python',
		'SASS/SCSS',
		'SQL',
		// Uncommon
		'Bash',
		'Datalog',
		'Kotlin',
		'Liquid Template Language',
		'Lisp',
		'Lua',
		'MIPS Assembly',
		'Nix',
		'R',
		'Regular Expressions',
		'VBA',
	],
	[SkillType.Technologies]: [
		// Common
		'Astro',
		'Cypress',
		'Django',
		'Docker',
		'Express.js',
		'FastAPI',
		'Firebase',
		'GatsbyJS',
		'GitHub Actions',
		'Jest',
		'Next.js',
		'Node.js',
		'Oracle DB',
		'Parcel',
		'PostCSS',
		'PostgreSQL',
		'Puppeteer',
		'React',
		'Selenium',
		'SolidJS',
		'SQLite',
		'Tailwind CSS',
		'Vercel',
		'Vite',
		'Vue',
		'Webpack',
		'Zod',
		// Uncommon
		'AVA',
		'Bun',
		'CUDA',
		'Deno',
		'Electron',
		'ESLint',
		'Gradle',
		'Grafana',
		'Gulp',
		'Jekyll',
		'Joi',
		'JSP',
		'JUnit',
		'Kubernetes',
		'Nano Stores',
		'NumPy',
		'OpenStack',
		'SonarQube',
		'Spring Framework',
		'Vitepress',
	],
	[SkillType.Tools]: [
		// Common
		'Claude Code',
		'Claude Desktop',
		'Continue',
		'Dependabot',
		'Git',
		'GitHub Copilot',
		'GitHub',
		'IntelliJ IDEA',
		'Jira',
		'Jupyter',
		'Linux',
		'Postman',
		'Visual Studio Code',
		'Visual Studio',
		// Uncommon
		'Android Studio',
		'Blender',
		'ChatGPT',
		'Gemini',
		'GIMP',
		'GraphiQL',
		'Inkscape',
		'Slack',
	],
	[SkillType.Topics]: [
		'Accessibility',
		'Agile Methodologies',
		'AI-Assisted Development',
		'Asynchronous Communication',
		'Automated Releases',
		'Automated Testing',
		'CI/CD',
		'Cloud Computing',
		'Code Review',
		'Component Design',
		'Containerization',
		'Cross-Functional Collaboration',
		'Database Design',
		'End-to-End Testing',
		'Frontend Architecture',
		'Integration Testing',
		'Load Testing',
		'OOP',
		'Regression Testing',
		'Requirements Analysis',
		'Responsive Design',
		'SOLID Principles',
		'State Management',
		'Static Code Analysis',
		'System Design',
		'Technical Documentation',
		'TDD',
		'Unit Testing',
		'Version Control',
		'Web Performance',
	],
} as const;
