/*
	Skills
	------
*/

import { type SkillsConfig, SkillType } from '../../types/content/skills.ts';

export const SKILLS_CONFIG: SkillsConfig = {
	[SkillType.Languages]: [
		// Common
		'C/C++',
		'CSS',
		'GraphQL',
		'HTML',
		'Java',
		'JavaScript/TypeScript',
		'JSX/TSX',
		'Python',
		'SASS/SCSS',
		'SQL',
		// Uncommon
		'Bash',
		'Datalog',
		'Kotlin',
		'Liquid Template Language',
		'Lisp',
		'Lua',
		'MIPS Assembly',
		'Nix',
		'R',
		'Regular Expressions',
		'VBA',
	],
	[SkillType.Technologies]: [
		// Common
		'Astro',
		'Cloudflare Workers',
		'Cypress',
		'daisyUI',
		'Django',
		'Docker',
		'Express.js',
		'FastAPI',
		'Firebase',
		'GatsbyJS',
		'GitHub Actions',
		'Jest',
		'Next.js',
		'Node.js',
		'Oracle DB',
		'Parcel',
		'Pinia',
		'Playwright',
		'PostCSS',
		'PostgreSQL',
		'Puppeteer',
		'React',
		'Selenium',
		'SolidJS',
		'SQLite',
		'Tailwind CSS',
		'Vercel',
		'Vite',
		'Vitest',
		'Vue',
		'Webpack',
		'Zod',
		// Uncommon
		'AVA',
		'Bun',
		'CUDA',
		'Deno',
		'Electron',
		'Gradle',
		'Grafana',
		'Gulp',
		'Jekyll',
		'Joi',
		'JSP',
		'JUnit',
		'Kubernetes',
		'Nano Stores',
		'NumPy',
		'Octokit',
		'OpenStack',
		'Pinia Colada',
		'SonarQube',
		'Spring Framework',
		'Vitepress',
		'Vue I18n',
		'VueUse',
	],
	[SkillType.Tools]: [
		// Common
		'Claude Code',
		'Claude Desktop',
		'Codex Desktop',
		'Continue',
		'Dependabot',
		'Git',
		'GitHub Copilot',
		'GitHub',
		'IntelliJ IDEA',
		'Jira',
		'Jupyter',
		'Linux',
		'Postman',
		'VS Code',
		'Visual Studio',
		// Uncommon
		'Android Studio',
		'Biome',
		'Blender',
		'ChatGPT',
		'ESLint',
		'Gemini',
		'GIMP',
		'GraphiQL',
		'Inkscape',
		'Oxfmt',
		'Oxlint',
		'Prettier',
		'Slack',
	],
	[SkillType.Topics]: [
		'Accessibility',
		'Agile Methodologies',
		'AI-Assisted Development',
		'Algorithm Design',
		'Asynchronous Communication',
		'Automated Releases',
		'Automated Testing',
		'Branding',
		'CI/CD',
		'Cloud Computing',
		'Code Review',
		'Complexity Analysis',
		'Component Design',
		'Containerization',
		'Cross-Functional Collaboration',
		'Data Structures',
		'Database Design',
		'End-to-End Testing',
		'Frontend Architecture',
		'Integration Testing',
		'Load Testing',
		'OOP',
		'OSS',
		'Regression Testing',
		'Requirements Analysis',
		'Responsive Design',
		'SEO',
		'SOLID Principles',
		'SSG',
		'State Management',
		'Static Code Analysis',
		'System Design',
		'TDD',
		'Technical Documentation',
		'UI/UX',
		'Unit Testing',
		'Version Control',
		'Web Design',
		'Web Performance',
	],
} as const;
