name: ♾️ CI
permissions:
  contents: read
on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
jobs:
  build:
    name: 🔨 Build
    runs-on: ubuntu-latest
    steps:
      - name: 📂 Checkout
        uses: actions/checkout@v4

      # Required for Puppeteer
      - name: 🛡️ Disable AppArmor
        run: echo 0 | sudo tee /proc/sys/kernel/apparmor_restrict_unprivileged_userns

      - name: 🥖 Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: 🗃️ Restore cache
        uses: actions/cache@v4
        with:
          path: |
            public
            .cache
          key: ${{ runner.os }}-gatsby-build-${{ hashFiles('public') }}
          restore-keys: |
            ${{ runner.os }}-gatsby-build-

      - name: 📥 Install dependencies
        run: bun i --frozen-lockfile

      - name: 🔨 Build with Gatsby
        env:
          PREFIX_PATHS: 'true'
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        run: bun run build
